# Generated by Django 2.2.4 on 2025-11-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
