# Generated by Django 2.2.4 on 2025-11-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='desc',
            new_name='desc_id',
        ),
        migrations.AddField(
            model_name='description',
            name='description',
            field=models.TextField(default='dddd'),
            preserve_default=False,
        ),
    ]
