# Generated by Django 2.2.4 on 2025-11-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_auto_20251104_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='desc_id',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='description',
            name='description',
        ),
    ]
