# Generated by Django 2.2.4 on 2025-11-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='course',
        ),
    ]
