# Generated by Django 5.2.8 on 2025-12-12 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_pomodorohistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
