# Generated by Django 2.2.4 on 2025-11-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
