# Generated by Django 2.2.4 on 2025-11-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_game_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
