# Generated by Django 2.2.4 on 2025-11-12 19:33

from django.db import migrations, models
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20251112_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to=my_app.models.user_directory_path),
        ),
    ]
