# Generated by Django 2.2.4 on 2025-11-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_user_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='banner',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
    ]
