# Generated by Django 5.2.8 on 2025-12-12 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=45)),
                ('notes', models.CharField(max_length=500)),
                ('date_found', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trees', to='my_app.user')),
            ],
        ),
    ]
