# Generated by Django 5.2.8 on 2025-12-12 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
