# Generated by Django 5.2.8 on 2025-12-12 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_tree_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_number', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_codes', to='my_app.tree')),
            ],
        ),
    ]
