# Generated by Django 5.2.8 on 2025-12-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_tree_zip_code_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
