# Generated by Django 5.2.8 on 2025-12-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='trees',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
