# Generated by Django 5.2.8 on 2025-12-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_zipcode_trees_delete_tree_delete_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=500)),
                ('date_found', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trees', to='my_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_number', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_codes', to='my_app.tree')),
            ],
        ),
    ]
