# Generated by Django 5.2.8 on 2025-12-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_remove_zipcode_trees_tree_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='zip_code',
            field=models.CharField(max_length=45),
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
