# Generated by Django 5.2.8 on 2025-12-12 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_tree_zip_code_delete_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_number', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tree',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_trees', to='my_app.zipcode'),
        ),
    ]
