# Generated by Django 5.2.8 on 2025-12-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_zipcode_alter_tree_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.zipcode'),
        ),
    ]
