# Generated by Django 5.2.8 on 2025-12-12 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_tree_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='zip_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='code_trees', to='my_app.zipcode'),
            preserve_default=False,
        ),
    ]
