# Generated by Django 5.2.8 on 2025-12-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_alter_tree_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='users_visits',
            field=models.ManyToManyField(related_name='visited_trees', to='my_app.user'),
        ),
    ]
