# Generated by Django 5.2.8 on 2025-12-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_tree_users_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_visited',
            field=models.BooleanField(default=False),
        ),
    ]
