# Generated by Django 5.2.8 on 2025-12-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_user_has_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='users_visits',
        ),
    ]
