# Generated by Django 5.2.8 on 2025-12-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_remove_tree_users_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_visited',
        ),
        migrations.AddField(
            model_name='tree',
            name='users_visits',
            field=models.ManyToManyField(related_name='visited_trees', to='my_app.user'),
        ),
    ]
