# Generated by Django 2.2.4 on 2025-10-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='user_id',
            new_name='dojo',
        ),
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='value'),
        ),
    ]
