# Generated by Django 2.2.4 on 2025-10-30 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0003_auto_20251030_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo',
            new_name='user_id',
        ),
    ]
