# Generated by Django 2.2.4 on 2025-10-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0004_auto_20251030_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='user_id',
            new_name='dojo',
        ),
    ]
