# Generated by Django 2.2.4 on 2025-11-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reviewed_by',
            new_name='added_by',
        ),
    ]
