# Generated by Django 2.2.4 on 2025-11-11 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20251111_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='added_by',
        ),
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='books', to='my_app.User'),
            preserve_default=False,
        ),
    ]
