# Generated by Django 2.2.4 on 2025-11-11 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20251111_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='added_by',
            new_name='user',
        ),
    ]
