# Generated by Django 2.2.4 on 2025-11-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dojo',
            old_name='name',
            new_name='dojo_name',
        ),
    ]
