# Generated by Django 2.2.4 on 2025-11-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20251108_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
